import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="./favicon1.ico" />
    </head>
    <App />
  </React.StrictMode>
);